# Generated by Django 2.1.3 on 2018-11-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
